"""MarketingPlugin — this plugin's BiffoPluginBase implementation.

Reacts to `biffo.core/UserCreated` by logging the new user, and carries an
idempotent seed for its baseline row. Replace both with real logic for your
own plugin — this exists to show a working, correctly-wired skeleton:
constructor -> manifest loading -> `self.api` -> `@self.subscribe`, exercised
end to end by the tests in `tests/test_marketing.py`.

**`on_install()` / `on_uninstall()` are not invoked.** They are required by
`BiffoPluginBase` and nothing calls them, so they are no-ops here and should
be no-ops in your plugin (biffo-template#709). An earlier version of this
skeleton seeded through `on_install()` — copying that gives you a seed that
silently never runs. This plugin has no seed — see the class docstring
actually goes.

Modelled directly on the RBAC reference plugin's
`services/rbac/src/rbac/plugin.py` (PR #76) in the biffo-template monorepo —
see that file (and its README) for a more elaborate example with multiple
tables, an event-driven side effect, and an in-process (non-CRUD) helper.
"""

from __future__ import annotations

from aws_lambda_powertools import Logger
from biffo_plugin_sdk import BiffoAPIClient, BiffoEvent, BiffoPluginBase, load_manifest

from .manifest import MANIFEST_PATH

logger = Logger()

_PLUGIN_BASE_PATH = "/api/v1/plugins/marketing"

# No seed data. A campaign studio has no meaningful baseline row: a campaign is
# something an operator creates deliberately, and inventing a starter one would
# put a row nobody asked for into a table the whole feature measures.


class MarketingPlugin(BiffoPluginBase):
    """The campaign studio's event-side plugin.

    Thin by design. The admin surface is an ASGI app the shared host mounts
    (``admin_app.py``); table CRUD is generated by Core from the manifest; and
    the agentic pipeline runs as Core agent runs rather than in this Lambda.
    What is left for this class is reacting to events, which today is nothing.
    """

    def __init__(self, api: BiffoAPIClient | None = None) -> None:
        manifest = load_manifest(MANIFEST_PATH)
        super().__init__(manifest, api=api)

        @self.subscribe("UserCreated")
        async def _on_user_created(event: BiffoEvent) -> None:
            await self._log_user_created(event)

    def on_install(self) -> None:
        """No-op. **Not invoked** — nothing calls it (biffo-template#709).

        `BiffoPluginBase` requires it, so it is defined; `biffo plugin
        install` does not run it, and neither does anything else. Put no
        logic here. This plugin seeds nothing — a campaign is created by an
        operator, and a starter row would pollute the very table this feature
        exists to measure.
        """
        return None

    def on_uninstall(self) -> None:
        """No-op. **Not invoked** — nothing calls it (biffo-template#709).

        There is no teardown moment for it to belong to either: `biffo plugin
        uninstall` removes the plugin's code and Terraform and deliberately
        leaves its tables in place (ADR-0003 section 9). Cleanup beyond that
        is a hand-written Alembic migration, not a hook.
        """
        return None

    async def _log_user_created(self, event: BiffoEvent) -> None:
        """Example event handler. Replace with real logic, or remove the
        `@self.subscribe` registration in `__init__` if your plugin doesn't
        need to react to this event."""
        logger.info(
            "New user created",
            extra={"tenant_id": event.tenant_id, "payload": event.payload},
        )
